apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kafka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dt-kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dt-kafka
    spec:
      containers:
        - name: deployment-kafka-pod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name:   KAFKA_ADVERTISED_LISTENERS
              value:  "PLAINTEXT://deployment-kafka-pod:9092"
            - name:   KAFKA_LISTENERS
              value:  "PLAINTEXT://:9092"
            - name:   KAFKA_ZOOKEEPER_CONNECT
              value:  "service-zookeeper.{{ $.Release.Namespace }}.svc.cluster.local:2181"
          ports:
            - name: http
              containerPort: 9092
              protocol: TCP