nameOverride:   ""
fullnameOverride:   ""

deployment:
  repository: JKOK005/distributed-trace
  tag: staging
  pullPolicy: IfNotPresent
  replicaCount: 1
  env:
    - name:   ROOT_PATH_ZK
      value:  distributed_trace
    - name:   SINK_PATH
      value:  sinks
    - name:   CONN_TIMEOUT
      value:  10
    - name:   KAFKA_TOPIC
      value:  distributedTrace
    - name:   KAFKA_PRODUCER_GROUP
      value:  distributed_trace_grp
    - name:   HEART_BEAT_NODE_PATH
      value:  heart_beat_nodes
    - name:   REGISTER_PUBLIC_PORT
      value:  4000

service:
  type: ClusterIP
  port: 80

nodes:
  - node1
  - node2