// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingMsg struct {
	HostAddr             string   `protobuf:"bytes,1,opt,name=hostAddr,proto3" json:"hostAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsg) Reset()         { *m = PingMsg{} }
func (m *PingMsg) String() string { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()    {}
func (*PingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *PingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsg.Unmarshal(m, b)
}
func (m *PingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsg.Marshal(b, m, deterministic)
}
func (m *PingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsg.Merge(m, src)
}
func (m *PingMsg) XXX_Size() int {
	return xxx_messageInfo_PingMsg.Size(m)
}
func (m *PingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsg proto.InternalMessageInfo

func (m *PingMsg) GetHostAddr() string {
	if m != nil {
		return m.HostAddr
	}
	return ""
}

type PingMsgResp struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsgResp) Reset()         { *m = PingMsgResp{} }
func (m *PingMsgResp) String() string { return proto.CompactTextString(m) }
func (*PingMsgResp) ProtoMessage()    {}
func (*PingMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *PingMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsgResp.Unmarshal(m, b)
}
func (m *PingMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsgResp.Marshal(b, m, deterministic)
}
func (m *PingMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsgResp.Merge(m, src)
}
func (m *PingMsgResp) XXX_Size() int {
	return xxx_messageInfo_PingMsgResp.Size(m)
}
func (m *PingMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsgResp proto.InternalMessageInfo

func (m *PingMsgResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type TraceReport struct {
	FromHostAddr          string   `protobuf:"bytes,1,opt,name=fromHostAddr,proto3" json:"fromHostAddr,omitempty"`
	FromHostMsgTimeNano   uint32   `protobuf:"varint,2,opt,name=fromHostMsgTimeNano,proto3" json:"fromHostMsgTimeNano,omitempty"`
	ToHostAddr            string   `protobuf:"bytes,3,opt,name=toHostAddr,proto3" json:"toHostAddr,omitempty"`
	ToHostMsgTimeNano     uint32   `protobuf:"varint,4,opt,name=toHostMsgTimeNano,proto3" json:"toHostMsgTimeNano,omitempty"`
	IsTransmissionSuccess bool     `protobuf:"varint,6,opt,name=isTransmissionSuccess,proto3" json:"isTransmissionSuccess,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TraceReport) Reset()         { *m = TraceReport{} }
func (m *TraceReport) String() string { return proto.CompactTextString(m) }
func (*TraceReport) ProtoMessage()    {}
func (*TraceReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *TraceReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceReport.Unmarshal(m, b)
}
func (m *TraceReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceReport.Marshal(b, m, deterministic)
}
func (m *TraceReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceReport.Merge(m, src)
}
func (m *TraceReport) XXX_Size() int {
	return xxx_messageInfo_TraceReport.Size(m)
}
func (m *TraceReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceReport.DiscardUnknown(m)
}

var xxx_messageInfo_TraceReport proto.InternalMessageInfo

func (m *TraceReport) GetFromHostAddr() string {
	if m != nil {
		return m.FromHostAddr
	}
	return ""
}

func (m *TraceReport) GetFromHostMsgTimeNano() uint32 {
	if m != nil {
		return m.FromHostMsgTimeNano
	}
	return 0
}

func (m *TraceReport) GetToHostAddr() string {
	if m != nil {
		return m.ToHostAddr
	}
	return ""
}

func (m *TraceReport) GetToHostMsgTimeNano() uint32 {
	if m != nil {
		return m.ToHostMsgTimeNano
	}
	return 0
}

func (m *TraceReport) GetIsTransmissionSuccess() bool {
	if m != nil {
		return m.IsTransmissionSuccess
	}
	return false
}

type TraceReportResp struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceReportResp) Reset()         { *m = TraceReportResp{} }
func (m *TraceReportResp) String() string { return proto.CompactTextString(m) }
func (*TraceReportResp) ProtoMessage()    {}
func (*TraceReportResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *TraceReportResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceReportResp.Unmarshal(m, b)
}
func (m *TraceReportResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceReportResp.Marshal(b, m, deterministic)
}
func (m *TraceReportResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceReportResp.Merge(m, src)
}
func (m *TraceReportResp) XXX_Size() int {
	return xxx_messageInfo_TraceReportResp.Size(m)
}
func (m *TraceReportResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceReportResp.DiscardUnknown(m)
}

var xxx_messageInfo_TraceReportResp proto.InternalMessageInfo

func (m *TraceReportResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*PingMsg)(nil), "message.PingMsg")
	proto.RegisterType((*PingMsgResp)(nil), "message.PingMsgResp")
	proto.RegisterType((*TraceReport)(nil), "message.TraceReport")
	proto.RegisterType((*TraceReportResp)(nil), "message.TraceReportResp")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xd1, 0x4a, 0xf3, 0x40,
	0x10, 0x85, 0xc9, 0xff, 0x4b, 0x9b, 0x4e, 0xad, 0xd5, 0x51, 0x21, 0x04, 0x91, 0x12, 0x10, 0x0a,
	0x4a, 0x94, 0xe8, 0x0b, 0x94, 0xde, 0x78, 0xd3, 0x22, 0x69, 0xc0, 0xeb, 0x98, 0x8c, 0xe9, 0x52,
	0x92, 0x0d, 0x3b, 0xab, 0x2f, 0xe1, 0x83, 0xfa, 0x1a, 0x92, 0x74, 0xdb, 0xa6, 0x1a, 0xf0, 0xc2,
	0xcb, 0x73, 0x66, 0xf6, 0xdb, 0x39, 0xb3, 0x0b, 0x47, 0x39, 0x31, 0xc7, 0x19, 0xb1, 0x5f, 0x2a,
	0xa9, 0x25, 0x76, 0x8d, 0xf6, 0xae, 0xa0, 0xfb, 0x24, 0x8a, 0x6c, 0xc6, 0x19, 0xba, 0x60, 0x2f,
	0x25, 0xeb, 0x49, 0x9a, 0x2a, 0xc7, 0x1a, 0x59, 0xe3, 0x5e, 0xb8, 0xd5, 0xde, 0x35, 0xf4, 0x4d,
	0x5b, 0x48, 0x5c, 0xe2, 0x05, 0xf4, 0x04, 0x2f, 0xde, 0x92, 0x84, 0x98, 0xeb, 0x5e, 0x3b, 0xdc,
	0x19, 0xde, 0xa7, 0x05, 0xfd, 0x48, 0xc5, 0x09, 0x85, 0x54, 0x4a, 0xa5, 0xd1, 0x83, 0xc3, 0x57,
	0x25, 0xf3, 0xc7, 0x7d, 0xf8, 0x9e, 0x87, 0x77, 0x70, 0xba, 0xd1, 0x33, 0xce, 0x22, 0x91, 0xd3,
	0x3c, 0x2e, 0xa4, 0xf3, 0x6f, 0x64, 0x8d, 0x07, 0x61, 0x5b, 0x09, 0x2f, 0x01, 0xb4, 0xdc, 0x32,
	0xff, 0xd7, 0xcc, 0x86, 0x83, 0x37, 0x70, 0xb2, 0x56, 0x4d, 0xde, 0x41, 0xcd, 0xfb, 0x59, 0xc0,
	0x07, 0x38, 0x17, 0x1c, 0xa9, 0xb8, 0xe0, 0x5c, 0x30, 0x0b, 0x59, 0x6c, 0xd2, 0x75, 0xea, 0x74,
	0xed, 0x45, 0xef, 0x16, 0x86, 0x8d, 0xa0, 0xbf, 0xaf, 0x26, 0x98, 0xc2, 0xe0, 0x59, 0xaa, 0x15,
	0xa9, 0x05, 0xa9, 0x77, 0x91, 0x10, 0x06, 0x60, 0x57, 0x8b, 0x9d, 0xcb, 0x94, 0xf0, 0xd8, 0x37,
	0xaf, 0xe2, 0x9b, 0x5d, 0xbb, 0x67, 0xdf, 0x9d, 0xea, 0x8a, 0xe0, 0xc3, 0x02, 0x34, 0xd3, 0x68,
	0xfd, 0x27, 0x14, 0x4e, 0x60, 0xb8, 0x9e, 0xbd, 0x3a, 0x35, 0x5d, 0x52, 0xb2, 0xc2, 0x5d, 0x63,
	0x23, 0x9a, 0xeb, 0xb4, 0xb9, 0x15, 0xe2, 0xa5, 0x53, 0xff, 0xa8, 0xfb, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x0b, 0x21, 0x2b, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerServiceClient interface {
	PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error)
}

type workerServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkerServiceClient(cc *grpc.ClientConn) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error) {
	out := new(PingMsgResp)
	err := c.cc.Invoke(ctx, "/message.WorkerService/PingNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
type WorkerServiceServer interface {
	PingNode(context.Context, *PingMsg) (*PingMsgResp, error)
}

// UnimplementedWorkerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServiceServer struct {
}

func (*UnimplementedWorkerServiceServer) PingNode(ctx context.Context, req *PingMsg) (*PingMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingNode not implemented")
}

func RegisterWorkerServiceServer(s *grpc.Server, srv WorkerServiceServer) {
	s.RegisterService(&_WorkerService_serviceDesc, srv)
}

func _WorkerService_PingNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).PingNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.WorkerService/PingNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).PingNode(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingNode",
			Handler:    _WorkerService_PingNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

// TransmitterServiceClient is the client API for TransmitterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransmitterServiceClient interface {
	PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error)
	ReportNodeCheck(ctx context.Context, in *TraceReport, opts ...grpc.CallOption) (*TraceReportResp, error)
}

type transmitterServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransmitterServiceClient(cc *grpc.ClientConn) TransmitterServiceClient {
	return &transmitterServiceClient{cc}
}

func (c *transmitterServiceClient) PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error) {
	out := new(PingMsgResp)
	err := c.cc.Invoke(ctx, "/message.TransmitterService/PingNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transmitterServiceClient) ReportNodeCheck(ctx context.Context, in *TraceReport, opts ...grpc.CallOption) (*TraceReportResp, error) {
	out := new(TraceReportResp)
	err := c.cc.Invoke(ctx, "/message.TransmitterService/ReportNodeCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransmitterServiceServer is the server API for TransmitterService service.
type TransmitterServiceServer interface {
	PingNode(context.Context, *PingMsg) (*PingMsgResp, error)
	ReportNodeCheck(context.Context, *TraceReport) (*TraceReportResp, error)
}

// UnimplementedTransmitterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransmitterServiceServer struct {
}

func (*UnimplementedTransmitterServiceServer) PingNode(ctx context.Context, req *PingMsg) (*PingMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingNode not implemented")
}
func (*UnimplementedTransmitterServiceServer) ReportNodeCheck(ctx context.Context, req *TraceReport) (*TraceReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportNodeCheck not implemented")
}

func RegisterTransmitterServiceServer(s *grpc.Server, srv TransmitterServiceServer) {
	s.RegisterService(&_TransmitterService_serviceDesc, srv)
}

func _TransmitterService_PingNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmitterServiceServer).PingNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.TransmitterService/PingNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmitterServiceServer).PingNode(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransmitterService_ReportNodeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmitterServiceServer).ReportNodeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.TransmitterService/ReportNodeCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmitterServiceServer).ReportNodeCheck(ctx, req.(*TraceReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransmitterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.TransmitterService",
	HandlerType: (*TransmitterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingNode",
			Handler:    _TransmitterService_PingNode_Handler,
		},
		{
			MethodName: "ReportNodeCheck",
			Handler:    _TransmitterService_ReportNodeCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
