// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingMsg struct {
	HostAddr             string   `protobuf:"bytes,1,opt,name=host_addr,json=hostAddr,proto3" json:"host_addr,omitempty"`
	MsgTimeNano          uint32   `protobuf:"varint,2,opt,name=msg_time_nano,json=msgTimeNano,proto3" json:"msg_time_nano,omitempty"`
	SeedNodeAddr         string   `protobuf:"bytes,3,opt,name=seed_node_addr,json=seedNodeAddr,proto3" json:"seed_node_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsg) Reset()         { *m = PingMsg{} }
func (m *PingMsg) String() string { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()    {}
func (*PingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *PingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsg.Unmarshal(m, b)
}
func (m *PingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsg.Marshal(b, m, deterministic)
}
func (m *PingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsg.Merge(m, src)
}
func (m *PingMsg) XXX_Size() int {
	return xxx_messageInfo_PingMsg.Size(m)
}
func (m *PingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsg proto.InternalMessageInfo

func (m *PingMsg) GetHostAddr() string {
	if m != nil {
		return m.HostAddr
	}
	return ""
}

func (m *PingMsg) GetMsgTimeNano() uint32 {
	if m != nil {
		return m.MsgTimeNano
	}
	return 0
}

func (m *PingMsg) GetSeedNodeAddr() string {
	if m != nil {
		return m.SeedNodeAddr
	}
	return ""
}

type PingMsgResp struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsgResp) Reset()         { *m = PingMsgResp{} }
func (m *PingMsgResp) String() string { return proto.CompactTextString(m) }
func (*PingMsgResp) ProtoMessage()    {}
func (*PingMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *PingMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsgResp.Unmarshal(m, b)
}
func (m *PingMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsgResp.Marshal(b, m, deterministic)
}
func (m *PingMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsgResp.Merge(m, src)
}
func (m *PingMsgResp) XXX_Size() int {
	return xxx_messageInfo_PingMsgResp.Size(m)
}
func (m *PingMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsgResp proto.InternalMessageInfo

func (m *PingMsgResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type TraceReport struct {
	FromHostAddr          string   `protobuf:"bytes,1,opt,name=from_host_addr,json=fromHostAddr,proto3" json:"from_host_addr,omitempty"`
	FromHostMsgTimeNano   uint32   `protobuf:"varint,2,opt,name=from_host_msg_time_nano,json=fromHostMsgTimeNano,proto3" json:"from_host_msg_time_nano,omitempty"`
	ToHostAddr            string   `protobuf:"bytes,3,opt,name=to_host_addr,json=toHostAddr,proto3" json:"to_host_addr,omitempty"`
	ToHostMsgTimeNano     uint32   `protobuf:"varint,4,opt,name=to_host_msg_time_nano,json=toHostMsgTimeNano,proto3" json:"to_host_msg_time_nano,omitempty"`
	SeedNodeAddr          string   `protobuf:"bytes,5,opt,name=seed_node_addr,json=seedNodeAddr,proto3" json:"seed_node_addr,omitempty"`
	IsTransmissionSuccess bool     `protobuf:"varint,6,opt,name=is_transmission_success,json=isTransmissionSuccess,proto3" json:"is_transmission_success,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TraceReport) Reset()         { *m = TraceReport{} }
func (m *TraceReport) String() string { return proto.CompactTextString(m) }
func (*TraceReport) ProtoMessage()    {}
func (*TraceReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *TraceReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceReport.Unmarshal(m, b)
}
func (m *TraceReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceReport.Marshal(b, m, deterministic)
}
func (m *TraceReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceReport.Merge(m, src)
}
func (m *TraceReport) XXX_Size() int {
	return xxx_messageInfo_TraceReport.Size(m)
}
func (m *TraceReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceReport.DiscardUnknown(m)
}

var xxx_messageInfo_TraceReport proto.InternalMessageInfo

func (m *TraceReport) GetFromHostAddr() string {
	if m != nil {
		return m.FromHostAddr
	}
	return ""
}

func (m *TraceReport) GetFromHostMsgTimeNano() uint32 {
	if m != nil {
		return m.FromHostMsgTimeNano
	}
	return 0
}

func (m *TraceReport) GetToHostAddr() string {
	if m != nil {
		return m.ToHostAddr
	}
	return ""
}

func (m *TraceReport) GetToHostMsgTimeNano() uint32 {
	if m != nil {
		return m.ToHostMsgTimeNano
	}
	return 0
}

func (m *TraceReport) GetSeedNodeAddr() string {
	if m != nil {
		return m.SeedNodeAddr
	}
	return ""
}

func (m *TraceReport) GetIsTransmissionSuccess() bool {
	if m != nil {
		return m.IsTransmissionSuccess
	}
	return false
}

type TraceReportResp struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceReportResp) Reset()         { *m = TraceReportResp{} }
func (m *TraceReportResp) String() string { return proto.CompactTextString(m) }
func (*TraceReportResp) ProtoMessage()    {}
func (*TraceReportResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *TraceReportResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceReportResp.Unmarshal(m, b)
}
func (m *TraceReportResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceReportResp.Marshal(b, m, deterministic)
}
func (m *TraceReportResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceReportResp.Merge(m, src)
}
func (m *TraceReportResp) XXX_Size() int {
	return xxx_messageInfo_TraceReportResp.Size(m)
}
func (m *TraceReportResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceReportResp.DiscardUnknown(m)
}

var xxx_messageInfo_TraceReportResp proto.InternalMessageInfo

func (m *TraceReportResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*PingMsg)(nil), "message.PingMsg")
	proto.RegisterType((*PingMsgResp)(nil), "message.PingMsgResp")
	proto.RegisterType((*TraceReport)(nil), "message.TraceReport")
	proto.RegisterType((*TraceReportResp)(nil), "message.TraceReportResp")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x4f, 0xea, 0x40,
	0x18, 0xc5, 0x53, 0xee, 0xbd, 0x3c, 0x3e, 0x5e, 0xf7, 0xce, 0x95, 0x80, 0x18, 0x13, 0xd2, 0xb8,
	0x60, 0x61, 0x08, 0x41, 0xe3, 0x9e, 0xe8, 0xc2, 0x0d, 0xc4, 0x14, 0xf6, 0x4d, 0xe9, 0x7c, 0x96,
	0x89, 0xe9, 0x4c, 0x33, 0xdf, 0xe0, 0x1f, 0xe2, 0xd6, 0x7f, 0xd6, 0x4c, 0x1f, 0x50, 0x91, 0x18,
	0x97, 0x3d, 0x3d, 0xf3, 0x3b, 0x27, 0x67, 0x06, 0x3a, 0x31, 0x12, 0x05, 0x11, 0xd2, 0x24, 0xd1,
	0xca, 0x28, 0x56, 0xcb, 0xbf, 0xdd, 0x04, 0x6a, 0x4f, 0x42, 0x46, 0x0b, 0x8a, 0xd8, 0x05, 0x34,
	0xb6, 0x8a, 0x8c, 0x1f, 0x70, 0xae, 0x07, 0xce, 0xc8, 0x19, 0x37, 0xbc, 0xba, 0x15, 0xe6, 0x9c,
	0x6b, 0xe6, 0x42, 0x3b, 0xa6, 0xc8, 0x37, 0x22, 0x46, 0x5f, 0x06, 0x52, 0x0d, 0x2a, 0x23, 0x67,
	0xdc, 0xf6, 0x9a, 0x31, 0x45, 0x6b, 0x11, 0xe3, 0x32, 0x90, 0x8a, 0x5d, 0x41, 0x87, 0x10, 0xb9,
	0x2f, 0x15, 0xc7, 0x8c, 0xf2, 0x2b, 0xa5, 0xb4, 0xac, 0xba, 0x54, 0x1c, 0x2d, 0xc9, 0xbd, 0x86,
	0x66, 0x9e, 0xe8, 0x21, 0x25, 0xec, 0x12, 0x40, 0x90, 0x4f, 0xbb, 0x30, 0x44, 0xa2, 0x34, 0xb6,
	0xee, 0x35, 0x04, 0xad, 0x32, 0xc1, 0x7d, 0xaf, 0x40, 0x73, 0xad, 0x83, 0x10, 0x3d, 0x4c, 0x94,
	0x36, 0x36, 0xe3, 0x59, 0xab, 0xd8, 0x3f, 0x6e, 0xda, 0xb2, 0xea, 0x63, 0xd1, 0xf6, 0x16, 0xfa,
	0x07, 0xd7, 0xa9, 0xde, 0xff, 0x0b, 0xfb, 0xa2, 0xd4, 0x7f, 0x04, 0x2d, 0xa3, 0x4a, 0xe4, 0xac,
	0x3d, 0x18, 0xb5, 0xe7, 0x4e, 0xa1, 0x57, 0x38, 0x3e, 0x53, 0x7f, 0xa7, 0xd4, 0x7f, 0x99, 0x75,
	0xf1, 0xed, 0x26, 0x7f, 0xbe, 0x6e, 0xc2, 0xee, 0xa0, 0x2f, 0xc8, 0x37, 0x3a, 0x90, 0x14, 0x0b,
	0x22, 0xa1, 0xe4, 0x7e, 0x91, 0x6a, 0xba, 0x48, 0x4f, 0xd0, 0xba, 0xf4, 0xb7, 0x58, 0x67, 0x0a,
	0xdd, 0xd2, 0x38, 0x3f, 0xd8, 0x73, 0xf6, 0xe6, 0xc0, 0xf9, 0x83, 0x20, 0xa3, 0xc5, 0x66, 0x67,
	0x90, 0xdb, 0xd3, 0x42, 0x46, 0x2b, 0xd4, 0xaf, 0x22, 0x44, 0x36, 0x83, 0xba, 0xbd, 0x1b, 0xdb,
	0x8b, 0xfd, 0x9d, 0xe4, 0x6f, 0x64, 0x92, 0x5f, 0xd7, 0xf0, 0xec, 0x58, 0x49, 0x03, 0xe7, 0xd0,
	0xcd, 0xe2, 0xed, 0xa9, 0xfb, 0x2d, 0x86, 0x2f, 0xec, 0x60, 0x2c, 0xb5, 0x1b, 0x0e, 0x4e, 0xa9,
	0x16, 0xb1, 0xa9, 0xa6, 0x8f, 0xf2, 0xe6, 0x23, 0x00, 0x00, 0xff, 0xff, 0x06, 0x4b, 0x3a, 0x3c,
	0xa6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DistributedTracingServiceClient is the client API for DistributedTracingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistributedTracingServiceClient interface {
	PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error)
	ReportNodeCheck(ctx context.Context, in *TraceReport, opts ...grpc.CallOption) (*TraceReportResp, error)
}

type distributedTracingServiceClient struct {
	cc *grpc.ClientConn
}

func NewDistributedTracingServiceClient(cc *grpc.ClientConn) DistributedTracingServiceClient {
	return &distributedTracingServiceClient{cc}
}

func (c *distributedTracingServiceClient) PingNode(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingMsgResp, error) {
	out := new(PingMsgResp)
	err := c.cc.Invoke(ctx, "/message.DistributedTracingService/PingNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedTracingServiceClient) ReportNodeCheck(ctx context.Context, in *TraceReport, opts ...grpc.CallOption) (*TraceReportResp, error) {
	out := new(TraceReportResp)
	err := c.cc.Invoke(ctx, "/message.DistributedTracingService/ReportNodeCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedTracingServiceServer is the server API for DistributedTracingService service.
type DistributedTracingServiceServer interface {
	PingNode(context.Context, *PingMsg) (*PingMsgResp, error)
	ReportNodeCheck(context.Context, *TraceReport) (*TraceReportResp, error)
}

// UnimplementedDistributedTracingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDistributedTracingServiceServer struct {
}

func (*UnimplementedDistributedTracingServiceServer) PingNode(ctx context.Context, req *PingMsg) (*PingMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingNode not implemented")
}
func (*UnimplementedDistributedTracingServiceServer) ReportNodeCheck(ctx context.Context, req *TraceReport) (*TraceReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportNodeCheck not implemented")
}

func RegisterDistributedTracingServiceServer(s *grpc.Server, srv DistributedTracingServiceServer) {
	s.RegisterService(&_DistributedTracingService_serviceDesc, srv)
}

func _DistributedTracingService_PingNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedTracingServiceServer).PingNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.DistributedTracingService/PingNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedTracingServiceServer).PingNode(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedTracingService_ReportNodeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedTracingServiceServer).ReportNodeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.DistributedTracingService/ReportNodeCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedTracingServiceServer).ReportNodeCheck(ctx, req.(*TraceReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributedTracingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.DistributedTracingService",
	HandlerType: (*DistributedTracingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingNode",
			Handler:    _DistributedTracingService_PingNode_Handler,
		},
		{
			MethodName: "ReportNodeCheck",
			Handler:    _DistributedTracingService_ReportNodeCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
