{{ range $node := .Values.nodes}}
apiVersion: v1
kind: Service
metadata:
  name: service-{{ $node }}
  labels:
    target.worker.node: {{ $node }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: 4000
      protocol: TCP
  selector:
    target.worker.node: {{ $node }}
---
{{ end }}
