# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wurstmeister/kafka
  tag: 2.12-2.2.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
